services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:${RABBITMQ_PORT}"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_USER: "${DATABASE_USER}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local